title: "SHUBHAM KUMAR"
email: shubhamkumar232001@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "THE-SHUBHAM-VERSE1.github.io/" 
twitter_username: SKUMAR
github_username:  THE-SHUBHAM-VERSE

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
